#!/bin/bash
 
dir=${@: -1}

if [ ! -d $dir ]; then 
    echo "Veuillez renseigner un nom de répertoire valide en dernier argument !"
    exit 1
fi

while getopts "oba" opt; do
  case $opt in
    o)
      find $dir -name *.old -print0 |xargs -0 -r rm
      ;;
    b)
      find $dir -name *.bak -print0 |xargs -0 -r rm
      ;;
    a)
      ./del -b -o $dir
      ;;
    *)
      echo "Option n'existe pas !"
      ;;
  esac
done
