--creation type
CREATE OR REPLACE TYPE COORDONNEE AS OBJECT (
Ville VARCHAR2(50),
CP NUMBER(5),
Tel VARCHAR2(14),
Fax VARCHAR2(50)
);

--insert
INSERT INTO EMP VALUES (14,'DUPUIS YVONNE', 'DEVELOPPEUR', NULL, 1, 17600, COORDONNEE('Lyon', 69000, '04725', NULL));
INSERT INTO EMP VALUES (15,'DUPOND JEAN', 'DEVELOPPEUR', NULL, 2, 14000, COORDONNEE('Paris', 75000, NULL, NULL));
INSERT INTO EMP VALUES (16,'CRINIERE BELLE', 'DEVELOPPEUR', NULL, 2, 1200, COORDONNEE('Grenoble', 38001,NULL, NULL));
INSERT INTO EMP VALUES (17,'AUBERT LOUIS', 'DEVELOPPEUR', NULL, 2, 12800, COORDONNEE('Lyon', 69100, '0478556585', NULL));
INSERT INTO EMP VALUES (18,'MAURI JOHN', 'DEVELOPPEUR', NULL, 2, 25000, COORDONNEE('Anglet', 64200, NULL, NULL));


--update
UPDATE EMP SET Coordonee = COORDONNEE('Anglet', '64200', NULL, NULL), salaire = 30000 WHERE numemp = 2;
UPDATE EMP SET Coordonee = COORDONNEE('Anglet', '64200', '0698098989', NULL), salaire = 20000 WHERE numemp = 3;

--5)
UPDATE EMP SET salaire = &salaire WHERE numemp = &numEmp;

--6)
SELECT (COORDONEE).Ville FROM EMP;
--OU SELECT E.COORDONEE.Ville FROM EMP E;

--7)
SELECT COUNT(DISTINCT (COORDONEE).Ville) FROM EMP;

--8)
SELECT NOM_COMPLET FROM EMP WHERE (COORDONEE).ville='Anglet';

--9)
SELECT NOM_COMPLET FROM EMP WHERE (COORDONEE).Tel IS NOT NULL;

--10)
SELECT e.COORDONEE.ville AS ville FROM EMP e JOIN DEPT D ON e.COORDONEE.ville = d.nomloc;

--11)
UPDATE EMP SET COORDONEE = COORDONNEE('Anglet',64200, '0768812826', 'jean@gmail.com') WHERE NOM_COMPLET = 'XAVIER Richard';
