--INSERT_EMP

create or replace PROCEDURE INSERT_EMP 
(
  NEMP IN NUMBER 
, NAME IN VARCHAR2 
, POSTE IN VARCHAR2 
, CHEF IN NUMBER 
, DEPART IN NUMBER 
, FLOUZE IN NUMBER 
, LAVILLE IN VARCHAR2 
, LECP IN NUMBER 
, TELEPHONE IN VARCHAR2 
, LEFAX IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO EMP VALUES (NEMP, NAME, POSTE, CHEF, DEPART, FLOUZE, COORDONNEE(LAVILLE,LECP,TELEPHONE,LEFAX));
END INSERT_EMP;

DECLARE
BEGIN
	INSERT_EMP(20, 'JEAN Bon', 'DEVELOPPEUR', NULL, 2, 300000, 'Bayonne', 64100, '0768812826', '08969549');
END;

--MAJ_EMP

CREATE OR REPLACE PROCEDURE MAJ_EMP 
(
  NAME IN VARCHAR2 
, SALARY IN NUMBER 
) AS 
BEGIN
  UPDATE EMP SET salaire = SALARY WHERE NOM_COMPLET = NAME;
  commit;
END MAJ_EMP;

DECLARE
BEGIN
	MAJ_EMP('XAVIER Richard', 15000);
END;

--COUNT_EMP

CREATE OR REPLACE FUNCTION COUNT_EMP RETURN NUMBER AS 

nombre NUMBER(4);

BEGIN
  SELECT COUNT(NUMEMP) INTO nombre FROM EMP;
  
  RETURN nombre;
END COUNT_EMP;

DECLARE
BEGIN
 dbms_output.put_line(COUNT_EMP());
END;

--COUNT_EMP(ville)

CREATE OR REPLACE FUNCTION COUNT_EMP2 
(
  LAVILLE IN VARCHAR2 
) RETURN NUMBER AS 

nombre NUMBER(4);

BEGIN
  SELECT COUNT(NUMEMP) INTO nombre FROM EMP e WHERE e.coordonee.ville = LAVILLE;
  RETURN nombre;
END COUNT_EMP2;

set serveroutput on;

DECLARE
BEGIN
 dbms_output.put_line(COUNT_EMP2('Anglet'));
END;